baseURL = "https://trycatch98.github.io/"
title = "Trycatch의 예외처리"
theme = "github-style"
copyright = "© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

[params]
  author = "Trycatch"
  description = "IT블로그"
  github = "trycatch98"
  email = "trycatch98@gmail.com"
  instagram = "trycatch__"
  utterances = "trycatch98/trycatch98.github.io"
  avatar = "https://trycatch98.github.io/images/avatar.png"
  url = "https://trycatch98.github.io"
